### ISSUE TITLE
ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils'

### ISSUE THREAD

**Issue by moda20** [EKOzkan/twAuto#11]
**Describe the bug**
an outdated import of chromeType from core.utils. it has been changed to `webdriver_manager.core.os_manager`
**To Reproduce**
follow the basic example using selenium 4+

**Additional context**
`webdriver_manager` related issue : https://github.com/SergeyPirogov/webdriver_manager/issues/563

**Comment by EKOzkan** [comment]
Thanks for reporting this bug. I am going to update the selenium part of the module soon. Since Twitter API does not requires much for tweeting operations with new plans, I was not going to update the module but from my experiences, API becomes useless in some situations bc of the "API specific" limitations.

**Comment by moda20** [comment]
Yeah the API has a weird bug that's been there for mroe than 6months where unlimited characters accounts wouldn't be able to post more than 280 characters when using the API. so this is kinda useful if not used in huge numbers (to not trip the ban factor) until that bug is fixed

**Comment by EKOzkan** [comment]
Can you try the latest update.

**Comment by moda20** [comment]
@EKOzkan yes it works now, hh i'll close this issue
